# Generated by Django 4.2.28 on 2026-04-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0004_project_task_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
